name: Zipper
on:
  push:
    branches: ["download"]
jobs:
  zip:
    permissions:
      contents: write # for git push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run zip
        run: |
         zip -r -9 download.zip ./
         
         if [ -n "$(git status --porcelain)" ]; then
           git config --global user.name "Github Actions"
           git config --global user.email "actions@github.com"
           git add download.zip
           git commit --allow-empty -m "打包"
           git push
         fi
